import {GuitarType, StringsCount} from "./const";
import electroGuitar1 from "./assets/img/electro-1.png";
import electroGuitar2 from "./assets/img/electro-2.png";
import electroGuitar3 from "./assets/img/electro-3.png";
import electroGuitar4 from "./assets/img/electro-4.png";
import ukulele1 from "./assets/img/ukulele-1.png";
import ukulele2 from "./assets/img/ukulele-2.png";

export const GUITARS = [
  {
    vendorCode: `SO757575`,
    name: `Честер Bass`,
    type: GuitarType.ELECTRO,
    reviewsCount: 15,
    strings: StringsCount.SEVEN,
    price: 17500,
    image: electroGuitar1,
  },
  {
    vendorCode: `TK129049`,
    name: `СURT Z300`,
    type: GuitarType.ELECTRO,
    reviewsCount: 9,
    strings: StringsCount.SEVEN,
    price: 29500,
    image: electroGuitar2,
  },
  {
    vendorCode: `RO111111`,
    name: `Roman LX`,
    type: GuitarType.UKULELE,
    reviewsCount: 21,
    strings: StringsCount.FOUR,
    price: 6800,
    image: ukulele1,
  },
  {
    vendorCode: `TK436457`,
    name: `СURT T300`,
    type: GuitarType.ELECTRO,
    reviewsCount: 15,
    strings: StringsCount.SIX,
    price: 30000,
    image: electroGuitar3,
  },
  {
    vendorCode: `DI192138`,
    name: `Dania Super`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 5,
    strings: StringsCount.SEVEN,
    price: 3500,
    image: ukulele2,
  },
  {
    vendorCode: `SO934345`,
    name: `Честер WX `,
    type: GuitarType.ELECTRO,
    reviewsCount: 17,
    strings: StringsCount.SIX,
    price: 15300,
    image: electroGuitar1,
  },
  {
    vendorCode: `DI082347`,
    name: `Dania VX`,
    type: GuitarType.UKULELE,
    reviewsCount: 5,
    strings: StringsCount.FOUR,
    price: 2200,
    image: ukulele1,
  },
  {
    vendorCode: `SO135646`,
    name: `Честер Plus `,
    type: GuitarType.ELECTRO,
    reviewsCount: 27,
    strings: StringsCount.SEVEN,
    price: 30000,
    image: electroGuitar4,
  },
  {
    vendorCode: `VO154751`,
    name: `Виолана 300`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 3,
    strings: StringsCount.SEVEN,
    price: 1700,
    image: ukulele2,
  },
  {
    vendorCode: `TK244556`,
    name: `СURT Clasic`,
    type: GuitarType.ELECTRO,
    reviewsCount: 20,
    strings: StringsCount.FOUR,
    price: 23000,
    image: electroGuitar1,
  },
  {
    vendorCode: `TK134663`,
    name: `СURT Z250`,
    type: GuitarType.ELECTRO,
    reviewsCount: 19,
    strings: StringsCount.FOUR,
    price: 18700,
    image: electroGuitar1,
  },
  {
    vendorCode: `SO123212`,
    name: `Честер 7X`,
    type: GuitarType.ELECTRO,
    reviewsCount: 30,
    strings: StringsCount.SEVEN,
    price: 35000,
    image: electroGuitar1,
  },
  {
    vendorCode: `SO123234`,
    name: `Честер 6V`,
    type: GuitarType.ELECTRO,
    reviewsCount: 28,
    strings: StringsCount.SIX,
    price: 14900,
    image: electroGuitar1,
  },
  {
    vendorCode: `VO519510`,
    name: `Виолана Mix`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 7,
    strings: StringsCount.SIX,
    price: 7600,
    image: ukulele2,
  },
  {
    vendorCode: `VO457369`,
    name: `Виолана 250x`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 19,
    strings: StringsCount.SIX,
    price: 6500,
    image: ukulele2,
  },
  {
    vendorCode: `FB625903`,
    name: `Фабио Лайт`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 26,
    strings: StringsCount.SEVEN,
    price: 12000,
    image: ukulele2,
  },
  {
    vendorCode: `FB576948`,
    name: `Фабио L100`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 31,
    strings: StringsCount.SEVEN,
    price: 9900,
    image: ukulele2,
  },
  {
    vendorCode: `LU012032`,
    name: `Liana Z200`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 28,
    strings: StringsCount.TWELVE,
    price: 8900,
    image: ukulele2,
  },
  {
    vendorCode: `LU546853`,
    name: `Liana Z100`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 34,
    strings: StringsCount.TWELVE,
    price: 10500,
    image: ukulele2,
  },
  {
    vendorCode: `LU458283`,
    name: `Liana Z300`,
    type: GuitarType.ACOUSTIC,
    reviewsCount: 9,
    strings: StringsCount.SIX,
    price: 13300,
    image: ukulele2,
  },
  {
    vendorCode: `RO324341`,
    name: `Roman RX`,
    type: GuitarType.UKULELE,
    reviewsCount: 37,
    strings: StringsCount.FOUR,
    price: 4800,
    image: ukulele1,
  },
  {
    vendorCode: `RO214235`,
    name: `Roman TX`,
    type: GuitarType.UKULELE,
    reviewsCount: 5,
    strings: StringsCount.FOUR,
    price: 1900,
    image: ukulele1,
  },
  {
    vendorCode: `DI132414`,
    name: `Dania U100`,
    type: GuitarType.UKULELE,
    reviewsCount: 23,
    strings: StringsCount.FOUR,
    price: 2500,
    image: ukulele1,
  },
  {
    vendorCode: `DI934754`,
    name: `Dania WR`,
    type: GuitarType.UKULELE,
    reviewsCount: 3,
    strings: StringsCount.FOUR,
    price: 3800,
    image: ukulele1,
  },
  {
    vendorCode: `DI034292`,
    name: `Dania LE`,
    type: GuitarType.UKULELE,
    reviewsCount: 10,
    strings: StringsCount.FOUR,
    price: 4100,
    image: ukulele1,
  },
  {
    vendorCode: `MI193214`,
    name: `Mirana V10`,
    type: GuitarType.UKULELE,
    reviewsCount: 14,
    strings: StringsCount.FOUR,
    price: 2700,
    image: ukulele1,
  },
  {
    vendorCode: `VO043244`,
    name: `Виолана Mini`,
    type: GuitarType.UKULELE,
    reviewsCount: 29,
    strings: StringsCount.FOUR,
    price: 6700,
    image: ukulele1,
  },
];
