import {GuitarType, GuitarTypeName} from "./const";

export const GUITARS = [
  {
    vendorCode: `SO757575`,
    name: `Честер Bass`,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 15,
    strings: 7,
    price: 17500,
  },
  {
    vendorCode: `TK129049`,
    name: `СURT Z300`,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 9,
    strings: 7,
    price: 29500,
  },
  {
    vendorCode: `RO111111`,
    name: `Roman LX`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 21,
    strings: 4,
    price: 6800,
  },
  {
    vendorCode: `TK436457`,
    name: `СURT T300`,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 15,
    strings: 6,
    price: 30000,
  },
  {
    vendorCode: `DI192138`,
    name: `Dania Super`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 5,
    strings: 7,
    price: 3500,
  },
  {
    vendorCode: `SO934345`,
    name: `Честер WX `,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 17,
    strings: 6,
    price: 15300,
  },
  {
    vendorCode: `DI082347`,
    name: `Dania VX`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 5,
    strings: 4,
    price: 2200,
  },
  {
    vendorCode: `SO135646`,
    name: `Честер Plus `,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 27,
    strings: 7,
    price: 30000,
  },
  {
    vendorCode: `VO154751`,
    name: `Виолана 300`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 3,
    strings: 7,
    price: 1700,
  },
  {
    vendorCode: `TK244556`,
    name: `СURT Clasic`,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 20,
    strings: 4,
    price: 23000,
  },
  {
    vendorCode: `TK134663`,
    name: `СURT Z250`,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 19,
    strings: 4,
    price: 18700,
  },
  {
    vendorCode: `SO123212`,
    name: `Честер 7X`,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 30,
    strings: 7,
    price: 35000,
  },
  {
    vendorCode: `SO123234`,
    name: `Честер 6V`,
    type: GuitarTypeName[GuitarType.ELECTRO],
    reviewsCount: 28,
    strings: 6,
    price: 14900,
  },
  {
    vendorCode: `VO519510`,
    name: `Виолана Mix`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 7,
    strings: 6,
    price: 7600,
  },
  {
    vendorCode: `VO457369`,
    name: `Виолана 250x`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 19,
    strings: 6,
    price: 6500,
  },
  {
    vendorCode: `FB625903`,
    name: `Фабио Лайт`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 26,
    strings: 7,
    price: 12000,
  },
  {
    vendorCode: `FB576948`,
    name: `Фабио L100`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 31,
    strings: 7,
    price: 9900,
  },
  {
    vendorCode: `LU012032`,
    name: `Liana Z200`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 28,
    strings: 12,
    price: 8900,
  },
  {
    vendorCode: `LU546853`,
    name: `Liana Z100`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 34,
    strings: 12,
    price: 10500,
  },
  {
    vendorCode: `LU458283`,
    name: `Liana Z300`,
    type: GuitarTypeName[GuitarType.ACOUSTIC],
    reviewsCount: 9,
    strings: 6,
    price: 13300,
  },
  {
    vendorCode: `RO324341`,
    name: `Roman RX`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 37,
    strings: 4,
    price: 4800,
  },
  {
    vendorCode: `RO214235`,
    name: `Roman TX`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 5,
    strings: 4,
    price: 1900,
  },
  {
    vendorCode: `DI132414`,
    name: `Dania U100`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 23,
    strings: 4,
    price: 2500,
  },
  {
    vendorCode: `DI934754`,
    name: `Dania WR`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 3,
    strings: 4,
    price: 3800,
  },
  {
    vendorCode: `DI034292`,
    name: `Dania LE`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 10,
    strings: 4,
    price: 4100,
  },
  {
    vendorCode: `MI193214`,
    name: `Mirana V10`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 14,
    strings: 4,
    price: 2700,
  },
  {
    vendorCode: `VO043244`,
    name: `Виолана Mini`,
    type: GuitarTypeName[GuitarType.UKULELE],
    reviewsCount: 29,
    strings: 4,
    price: 6700,
  },
];
